import { DrawerModal, DrawerSection, DrawerField, inputCls } from "@/shared/components/DrawerModal";
import { ConfirmModal } from "@/shared/components/ConfirmModal";
import { Combobox } from "@/shared/components/Combobox";
import { SearchInput } from "@/shared/components/SearchInput";
import { Skeleton } from "@/shared/components/Skeleton";
import { TablePagination } from "@/shared/components/TablePagination";
import { Checkbox } from "@/shared/components/ui/checkbox";
import { cn } from "@/shared/utils";
import { PARTNER_KIND_OPTS, CURRENCY_OPTS, PARTNER_ROLE_OPTS } from "@/modules/partners/constants";
import { PageHeader, RowActions, StatusBadge } from "./shared";

export function PartnersTabView(p: any) {
  const { t, openNew, searchInput, handleSearchInput, items, loading, fetchError, kindLabel, openEdit, setDeleteTarget, page, pageSize, total, totalPages, setPage, handlePageSize, drawerOpen, closeDrawer, isDirty, editing, saving, handleSave, form, setField, contactRows, setContactField, removeContactRow, addContactRow, bankRows, setBankField, removeBankRow, addBankRow, saveError, deleteTarget, deleting, handleDelete } = p;
  return <div>
    <PageHeader title={t("doitac.title")} desc={t("doitac.desc")} onAdd={openNew} />
    <div className="mb-3"><SearchInput placeholder="Tìm mã, tên hoặc MST..." value={searchInput} onChange={handleSearchInput} className="max-w-[280px]" /></div>
    <PartnerTable {...{ t, items, loading, fetchError, kindLabel, openEdit, setDeleteTarget }} />
    <TablePagination page={page} pageSize={pageSize} total={total} totalPages={totalPages} onPage={setPage} onPageSize={handlePageSize} />
    <PartnerDrawer {...{ drawerOpen, closeDrawer, isDirty, editing, saving, handleSave, form, setField, contactRows, setContactField, removeContactRow, addContactRow, bankRows, setBankField, removeBankRow, addBankRow, saveError }} />
    <ConfirmModal open={!!deleteTarget} title="Xóa đối tác?" message={`Bạn có chắc muốn xóa đối tác "${deleteTarget?.name}"? Hành động này không thể hoàn tác.`} confirmLabel="Xóa" loading={deleting} onConfirm={handleDelete} onCancel={() => setDeleteTarget(null)} />
  </div>;
}

function PartnerTable({ t, items, loading, fetchError, kindLabel, openEdit, setDeleteTarget }: any) {
  const headers = [t("doitac.headers.code"), t("doitac.headers.name"), t("doitac.headers.kind"), t("doitac.headers.taxCode"), t("doitac.headers.phone"), t("doitac.headers.status"), ""];
  return <div className="bg-surface border border-border rounded-[10px] overflow-x-auto card-shadow"><table className="w-full border-collapse" style={{ minWidth: 680 }}><thead><tr>{headers.map((h, i) => <th key={i} className={cn("text-left text-[11px] font-semibold text-[color:var(--muted-fg)] px-[10px] py-[8px] border-b border-border uppercase tracking-[0.05em]", i === 6 && "w-[80px]")}>{h}</th>)}</tr></thead><tbody>{loading && Array.from({ length: 5 }).map((_, i) => <SkeletonRow key={i} />)}{!loading && fetchError && <tr><td colSpan={7} className="text-center text-xs text-[color:var(--warn-fg)] py-8">{fetchError}</td></tr>}{!loading && !fetchError && items.length === 0 && <tr><td colSpan={7} className="text-center text-xs text-[color:var(--faint)] py-8">{t("common.noData")}</td></tr>}{items.map((bp: any) => <PartnerRow key={bp.id} {...{ bp, kindLabel, openEdit, setDeleteTarget }} />)}</tbody></table></div>;
}
function SkeletonRow() { return <tr>{[14, 36, 20, 20, 24, 16, 0].map((w, j) => <td key={j} className="px-[10px] py-[10px] border-b border-[color:var(--border-light)]">{w > 0 && <Skeleton className={`h-3 w-${w}`} />}</td>)}</tr>; }
function PartnerRow({ bp, kindLabel, openEdit, setDeleteTarget }: any) { return <tr className="hover:bg-surface-hover"><td className="text-xs px-[10px] py-[10px] border-b border-[color:var(--border-light)] font-mono font-semibold text-[color:var(--muted-fg)]">{bp.code}</td><td className="text-xs px-[10px] py-[10px] border-b border-[color:var(--border-light)] font-medium">{bp.name}</td><td className="text-xs px-[10px] py-[10px] border-b border-[color:var(--border-light)] text-[color:var(--muted-fg)]">{kindLabel(bp.partner_kind)}</td><td className="text-xs px-[10px] py-[10px] border-b border-[color:var(--border-light)] font-mono text-[color:var(--muted-fg)]">{bp.tax_code || "—"}</td><td className="text-xs px-[10px] py-[10px] border-b border-[color:var(--border-light)] text-[color:var(--muted-fg)]">{bp.phone || "—"}</td><td className="text-xs px-[10px] py-[10px] border-b border-[color:var(--border-light)]"><StatusBadge active={bp.is_active} /></td><td className="text-xs px-[10px] py-[10px] border-b border-[color:var(--border-light)]"><RowActions onEdit={() => openEdit(bp)} onDelete={() => setDeleteTarget(bp)} /></td></tr>; }

function PartnerDrawer({ drawerOpen, closeDrawer, isDirty, editing, saving, handleSave, form, setField, contactRows, setContactField, removeContactRow, addContactRow, bankRows, setBankField, removeBankRow, addBankRow, saveError }: any) {
  return <DrawerModal open={drawerOpen} onClose={closeDrawer} confirmOnClose={isDirty && !editing} title={editing ? "Chỉnh sửa đối tác" : "Thêm đối tác mới"} subtitle={editing ? editing.name : "Điền thông tin bên dưới"} panelClassName="partner-drawer-panel" bodyClassName="partner-drawer-body" actions={[{ label: "Hủy", onClick: closeDrawer }, { label: editing ? "Lưu thay đổi" : "Thêm mới", primary: true, loading: saving, disabled: saving, onClick: handleSave }]}><div className="partner-drawer-grid"><MainInfoCard {...{ form, setField }} /><ContactsCard {...{ contactRows, setContactField, removeContactRow, addContactRow }} /><BanksCard {...{ bankRows, setBankField, removeBankRow, addBankRow }} /><RoleCard {...{ form, setField }} /></div>{saveError && <div className="text-xs text-[color:var(--warn-fg)] bg-[color:var(--warn-bg)] border border-[color:var(--warn-fg)]/30 rounded-lg px-3 py-2">{saveError}</div>}</DrawerModal>;
}
function MainInfoCard({ form, setField }: any) { return <div className="partner-card partner-card-main"><DrawerSection title="Thông tin đối tác"><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-x-3"><DrawerField label="Mã đối tác" required><input type="text" className={inputCls} value={form.code} onChange={(e) => setField("code", e.target.value)} placeholder="VD: KH001" /></DrawerField><DrawerField label="Tên đối tác" required><input type="text" className={inputCls} value={form.name} onChange={(e) => setField("name", e.target.value)} placeholder="Tên đầy đủ" /></DrawerField><DrawerField label="Tên hiển thị"><input type="text" className={inputCls} value={form.display_name} onChange={(e) => setField("display_name", e.target.value)} placeholder="Tên ngắn gọn (tùy chọn)" /></DrawerField><DrawerField label="Loại đối tác"><Combobox options={PARTNER_KIND_OPTS} value={form.partner_kind} onChange={(v) => setField("partner_kind", v || "ORGANIZATION")} allowClear={false} /></DrawerField><DrawerField label="Mã số thuế"><input type="text" className={inputCls} value={form.tax_code} onChange={(e) => setField("tax_code", e.target.value)} placeholder="0123456789" /></DrawerField><DrawerField label="Điện thoại"><input type="text" className={inputCls} value={form.phone} onChange={(e) => setField("phone", e.target.value)} placeholder="0912 345 678" /></DrawerField><DrawerField label="Email"><input type="email" className={inputCls} value={form.email} onChange={(e) => setField("email", e.target.value)} placeholder="contact@example.com" /></DrawerField><div className="md:col-span-2 xl:col-span-3"><DrawerField label="Địa chỉ"><input type="text" className={inputCls} value={form.address} onChange={(e) => setField("address", e.target.value)} placeholder="Địa chỉ đầy đủ" /></DrawerField></div><div className="md:col-span-2 xl:col-span-3"><DrawerField label="Ghi chú"><textarea className={inputCls} rows={2} value={form.note} onChange={(e) => setField("note", e.target.value)} /></DrawerField></div><DrawerField label="Trạng thái"><label className="flex items-center gap-2 cursor-pointer"><Checkbox checked={form.is_active} onCheckedChange={(v) => setField("is_active", v === true)} /><span className="text-xs text-foreground">Đang hoạt động</span></label></DrawerField></div></DrawerSection></div>; }
function ContactsCard({ contactRows, setContactField, removeContactRow, addContactRow }: any) { return <div className="partner-card partner-card-contact"><DrawerSection title={`Liên hệ (${contactRows.length})`}><div className="partner-sublist">{contactRows.map((row: any, idx: number) => <div key={row.tempId} className="partner-subitem"><div className="partner-subitem-head"><span>Liên hệ {idx + 1}</span><button type="button" onClick={() => removeContactRow(idx)}>Xóa</button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-x-2"><DrawerField label="Họ và tên"><input type="text" className={inputCls} value={row.full_name} onChange={(e) => setContactField(idx, "full_name", e.target.value)} placeholder="Tên người liên hệ" /></DrawerField><DrawerField label="Chức vụ"><input type="text" className={inputCls} value={row.position} onChange={(e) => setContactField(idx, "position", e.target.value)} placeholder="VD: Kế toán trưởng" /></DrawerField><DrawerField label="Điện thoại"><input type="text" className={inputCls} value={row.phone} onChange={(e) => setContactField(idx, "phone", e.target.value)} placeholder="0912 345 678" /></DrawerField><DrawerField label="Email"><input type="email" className={inputCls} value={row.email} onChange={(e) => setContactField(idx, "email", e.target.value)} placeholder="contact@example.com" /></DrawerField></div><div className="partner-check-row"><Check checked={row.is_default_receiver} onChange={(v: boolean) => setContactField(idx, "is_default_receiver", v)} label="Người nhận mặc định" /><Check checked={row.is_default_payer} onChange={(v: boolean) => setContactField(idx, "is_default_payer", v)} label="Người trả mặc định" /><Check checked={row.is_active} onChange={(v: boolean) => setContactField(idx, "is_active", v)} label="Đang hoạt động" /></div></div>)}</div><button type="button" className="partner-add-line" onClick={addContactRow}>+ Thêm liên hệ</button></DrawerSection></div>; }
function BanksCard({ bankRows, setBankField, removeBankRow, addBankRow }: any) { return <div className="partner-card partner-card-bank"><DrawerSection title={`Tài khoản ngân hàng (${bankRows.length})`}><div className="partner-sublist">{bankRows.map((row: any, idx: number) => <div key={row.tempId} className="partner-subitem"><div className="partner-subitem-head"><span>Tài khoản {idx + 1}</span><button type="button" onClick={() => removeBankRow(idx)}>Xóa</button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-x-2"><DrawerField label="Tên ngân hàng"><input type="text" className={inputCls} value={row.bank_name} onChange={(e) => setBankField(idx, "bank_name", e.target.value)} placeholder="VD: Vietcombank" /></DrawerField><DrawerField label="Chi nhánh"><input type="text" className={inputCls} value={row.bank_branch} onChange={(e) => setBankField(idx, "bank_branch", e.target.value)} placeholder="VD: Hà Nội" /></DrawerField><DrawerField label="Số tài khoản"><input type="text" className={inputCls} value={row.account_number} onChange={(e) => setBankField(idx, "account_number", e.target.value)} placeholder="0071001xxx" /></DrawerField><DrawerField label="Chủ tài khoản"><input type="text" className={inputCls} value={row.account_holder} onChange={(e) => setBankField(idx, "account_holder", e.target.value)} /></DrawerField><DrawerField label="Tiền tệ"><Combobox options={CURRENCY_OPTS} value={row.currency} onChange={(v) => setBankField(idx, "currency", v || "VND")} allowClear={false} /></DrawerField></div><div className="partner-check-row"><Check checked={row.is_default} onChange={(v: boolean) => setBankField(idx, "is_default", v)} label="Tài khoản mặc định" /><Check checked={row.is_active} onChange={(v: boolean) => setBankField(idx, "is_active", v)} label="Đang hoạt động" /></div></div>)}</div><button type="button" className="partner-add-line" onClick={addBankRow}>+ Thêm tài khoản ngân hàng</button></DrawerSection></div>; }
function RoleCard({ form, setField }: any) { return <div className="partner-card partner-card-role"><DrawerSection title="Vai trò đối tác"><div className="grid grid-cols-1 gap-x-3"><DrawerField label="Tạo / cập nhật vai trò"><Check checked={form.role_enabled} onChange={(v: boolean) => setField("role_enabled", v)} label="Lưu vai trò cho đối tác này" /></DrawerField><DrawerField label="Vai trò"><Combobox options={PARTNER_ROLE_OPTS} value={form.role} onChange={(v) => setField("role", v || "CUSTOMER")} allowClear={false} /></DrawerField><DrawerField label="Trạng thái vai trò"><Check checked={form.role_is_active} onChange={(v: boolean) => setField("role_is_active", v)} label="Đang hoạt động" /></DrawerField></div></DrawerSection></div>; }
function Check({ checked, onChange, label }: any) { return <label className="flex items-center gap-2 cursor-pointer"><Checkbox checked={checked} onCheckedChange={(v) => onChange(v === true)} /><span className="text-xs text-foreground">{label}</span></label>; }
