import type { QuoteFinancialItem } from "./GarageCasePreview.type";

export const buildFinancialItems = (
  rawData: any,
  caseData: any,
  grossProfit?: any,
): QuoteFinancialItem[] => {
  const tongTienHang = Number(rawData?.TongTienHang || 0);
  const tongChiPhi = Number(
    grossProfit?.ChiPhi ?? caseData?.chiPhi ?? rawData?.ChiPhi ?? 0,
  );
  const doanhThu = Number(
    grossProfit?.DoanhThu ?? caseData?.doanhThu ?? rawData?.TongTienHang ?? 0,
  );
  const loiNhuan = Number(
    grossProfit?.LoiNhuan ??
      caseData?.loiNhuan ??
      rawData?.LoiNhuan ??
      doanhThu - tongChiPhi,
  );

  return [
    {
      id: "tong-tien-hang",
      order: 1,
      group: "REVENUE",
      labelKey: "cases.quotePreview.fin.tongTienHang",
      defaultLabel: "1. Tổng tiền hàng (chưa thuế)",
      amount: tongTienHang,
      payer: "NONE",
      tone: "default",
    },
    {
      id: "tien-chiet-khau",
      order: 2,
      group: "DEDUCTION",
      labelKey: "cases.quotePreview.fin.tienChietKhau",
      defaultLabel: "2. Tiền chiết khấu",
      rate: Number(rawData?.TyLeChietKhau || 0),
      amount: Number(rawData?.TienChietKhau || 0),
      payer: "GARAGE",
      tone: "danger",
    },
    {
      id: "tien-feedback",
      order: 3,
      group: "DEDUCTION",
      labelKey: "cases.quotePreview.fin.tienFeedback",
      defaultLabel: "3. Chiết khấu phản hồi (Feedback)",
      rate: Number(rawData?.TyLeFeedback || 0),
      amount: Number(rawData?.TienFeedback || 0),
      payer: "GARAGE",
      tone: "danger",
    },
    {
      id: "tien-thue",
      order: 4,
      group: "REVENUE",
      labelKey: "cases.quotePreview.fin.tienThue",
      defaultLabel: "4. Thuế VAT",
      rate: Number(rawData?.ThueSuat || 0),
      amount: Number(rawData?.TienThue || 0),
      payer: "NONE",
      tone: "default",
    },
    {
      id: "tong-thanh-toan",
      order: 5,
      group: "PAYMENT",
      labelKey: "cases.quotePreview.fin.tongThanhToan",
      defaultLabel: "5. Tổng tiền thanh toán (sau thuế)",
      amount: Number(rawData?.TongTienThanhToan || caseData?.tienCoThue || 0),
      payer: "NONE",
      tone: "primary",
    },
    {
      id: "kh-thanh-toan",
      order: 6,
      group: "PAYMENT",
      labelKey: "cases.quotePreview.fin.khThanhToan",
      defaultLabel: "6. Khách hàng thanh toán",
      amount: Number(rawData?.TienThanhToanKH || 0),
      payer: "KH",
      tone: "default",
    },
    {
      id: "bh-thanh-toan",
      order: 7,
      group: "PAYMENT",
      labelKey: "cases.quotePreview.fin.bhThanhToan",
      defaultLabel: "7. Bảo hiểm thanh toán",
      amount: Number(rawData?.TienThanhToanBH || 0),
      payer: "BH",
      tone: "default",
    },
    {
      id: "hh-bao-hiem",
      order: 8,
      group: "COMMISSION",
      labelKey: "cases.quotePreview.fin.hhBaoHiem",
      defaultLabel: "8. Hoa hồng bảo hiểm",
      rate: Number(rawData?.TyLeHoaHongBaoHiem || 0),
      amount: Number(rawData?.TienHoaHongBaoHiem || 0),
      payer: "GARAGE",
      tone: "danger",
    },
    {
      id: "hh-moi-gioi",
      order: 9,
      group: "COMMISSION",
      labelKey: "cases.quotePreview.fin.hhMoiGioi",
      defaultLabel: "9. Hoa hồng môi giới",
      rate: Number(rawData?.TyLeHoaHongMoiGioi || 0),
      amount: Number(rawData?.TienHoaHongMoiGioi || 0),
      payer: "GARAGE",
      tone: "danger",
    },
    {
      id: "da-thanh-toan",
      order: 10,
      group: "PAYMENT",
      labelKey: "cases.quotePreview.fin.daThanhToan",
      defaultLabel: "10. Đã thu thực tế",
      amount: Number(rawData?.TienDaThanhToan || 0),
      payer: "NONE",
      tone: "success",
    },
    {
      id: "con-phai-thu",
      order: 11,
      group: "PAYMENT",
      labelKey: "cases.quotePreview.fin.conPhaiThu",
      defaultLabel: "11. Còn phải thu",
      amount: Number(rawData?.TienConPhaiThanhToan || 0),
      payer: "NONE",
      tone: "warning",
    },
    {
      id: "gia-von-phu-tung",
      order: 12,
      group: "PROFIT",
      labelKey: "cases.quotePreview.fin.giaVonPhuTung",
      defaultLabel: "12. Giá vốn phụ tùng",
      amount: Number(grossProfit?.GiaVonPhuTung || 0),
      payer: "GARAGE",
      tone: "muted",
    },
    {
      id: "tong-chi-phi",
      order: 13,
      group: "PROFIT",
      labelKey: "cases.quotePreview.fin.tongChiPhi",
      defaultLabel: "13. Tổng chi phí vụ việc",
      amount: tongChiPhi,
      payer: "GARAGE",
      tone: "danger",
    },
    {
      id: "loi-nhuan-gop",
      order: 14,
      group: "PROFIT",
      labelKey: "cases.quotePreview.fin.loiNhuanGop",
      defaultLabel: "14. Lợi nhuận gộp (tạm tính)",
      amount: loiNhuan,
      payer: "NONE",
      tone: "success",
    },
  ];
};
